### ISSUE TITLE
Error in densenet model

### ISSUE THREAD

**Issue by kHarshit** [Fangyh09/pytorch-receptive-field#5]
The code throws an error in the case of densenet model possibly due to presence of block names such as `_DenseBlock`. If I print the `class_name`, it stucks at `_DenseBlock`.
```
_DenseBlock
class_name: _DenseBlock
```

```
Traceback (most recent call last):
  File "bts_sequence.py", line 240, in <module>
    test(args)
  File "bts_sequence.py", line 92, in test
    receptive_field_dict = receptive_field.receptive_field(model, (3, 256, 256))
  File "/kharshit/bts/pytorch/receptive_field.py", line 119, in receptive_field
    model(x, 518.8579)
  File "/kharshit/miniconda3/envs/pylatest/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/kharshit/miniconda3/envs/pylatest/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/kharshit/miniconda3/envs/pylatest/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "models/frames_not18_densenet121_pretrained_nyu/frames_not18_densenet121_pretrained_nyu.py", line 331, in forward
    skip_feat = self.encoder(x)
  File "/kharshit/miniconda3/envs/pylatest/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "models/frames_not18_densenet121_pretrained_nyu/frames_not18_densenet121_pretrained_nyu.py", line 316, in forward
    feature = v(features[-1])
  File "/kharshit/miniconda3/envs/pylatest/lib/python3.7/site-packages/torch/nn/modules/module.py", line 549, in __call__
    hook_result = hook(self, input, result)
  File "/kharshit/bts/pytorch/receptive_field.py", line 66, in hook
    raise ValueError("module not ok")
ValueError: module not ok
```

**Comment by Fangyh09** [comment]
@kHarshit Yes, _DenseBlock is not supported currently. Welcome contribute to it!

**Comment by SysOverdrive** [comment]
Fangy09 Maybe you could give some tips on how to integrate the DenseBlock ?
